project_id = "aasihxqsasjpszqjlbid"

[functions.admin-users]
verify_jwt = false

[functions.send-invitation]
verify_jwt = false

[functions.import-framework]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = false