// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Sécurité (F-702) : tokens stockés en sessionStorage plutôt que localStorage.
// Conséquence UX : la session est purgée à la fermeture de l'onglet/navigateur
// (pas de "rester connecté" entre sessions de navigateur). Mitigation XSS :
// réduit drastiquement la fenêtre d'exfiltration des JWT en cas d'injection.
// Couplé à la CSP stricte d'index.html (script-src 'self', pas d'unsafe-eval).
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: sessionStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});